model: ## hierarchical
  selected_model: "LSTMInputCell" # model name

  ## deep learning hyperparameters
  use_fc: False
  use_adaptive_lr: True
  multiply_factor: 0.9
  batch_size: 16
  dropout: 0.2
  lr: 0.01  # learning rate
  patience: 500 # for early stopping
  epochs: 1000

  hidden_size: 8
  num_layers: 1
  bidirectional: False
  r: 8
  d_a: 4

  ## Deep learning criterions and save log
  criterions: ["loss", "accuracy", "f1_score", "precision", "recall"]