model: ## hierarchical
  selected_model: "FCN_laststep" # model name

  ## deep learning hyperparameters
  use_fc: True
  use_pooling: False
  use_adaptive_lr: True
  multiply_factor: 0.9
  batch_size: 32
  val_batch_size: 64
  dropout: 0.3
  lr: 0.001  # learning rate
  patience: 400 # for early stopping
  epochs: 1000

  kernel_size: [7, 7, 5, 5, 3, 3]
  ch_out: [32, 64, 64, 64, 64, 32, 32, 32]

  ## Deep learning criterions and save log
  criterions: ["loss", "accuracy", "f1_score", "precision", "recall"]
