model: ## hierarchical
  selected_model: LSTM # model name

  ## deep learning hyperparameters
  use_fc: False
  use_adaptive_lr: True
  multiply_factor: 0.9
  batch_size: 16
  val_batch_size: 100
  dropout: 0.2
  lr: 0.01  # learning rate
  patience: 400 # for early stopping
  epochs: 2000

  hidden_size: 32
  num_layers: 1
  bidirectional: False

  ## Deep learning criterions and save log
  criterions: ["loss", "accuracy", "f1_score", "precision", "recall"]
